---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-server
  namespace: beta-app
  labels:
    app.kubernetes.io/name: authorization-server
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: authorization-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authorization-server
    spec:
      containers:
        - name: authorization-server-api
          image: 306472407007.dkr.ecr.ap-south-1.amazonaws.com/ibs-skillset-happystays/authorization-server:db26e4e
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9000
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          env:
            - name: HOST_UI
              valueFrom:
                configMapKeyRef:
                  name: ui-config
                  key: HOST_URL
            - name: HOST_IP
              value: authorization-server
            - name: HOST_CONFIG
              value: config-server
            - name: HOST_DB
              value: postgres-service.db-system
            - name: HOST_REGISTRY
              value: service-registry
